// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: hello/pkg/grpc/pb/hello.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FooRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FooRequest) Reset() {
	*x = FooRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_pkg_grpc_pb_hello_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FooRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FooRequest) ProtoMessage() {}

func (x *FooRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hello_pkg_grpc_pb_hello_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FooRequest.ProtoReflect.Descriptor instead.
func (*FooRequest) Descriptor() ([]byte, []int) {
	return file_hello_pkg_grpc_pb_hello_proto_rawDescGZIP(), []int{0}
}

type FooReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FooReply) Reset() {
	*x = FooReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hello_pkg_grpc_pb_hello_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FooReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FooReply) ProtoMessage() {}

func (x *FooReply) ProtoReflect() protoreflect.Message {
	mi := &file_hello_pkg_grpc_pb_hello_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FooReply.ProtoReflect.Descriptor instead.
func (*FooReply) Descriptor() ([]byte, []int) {
	return file_hello_pkg_grpc_pb_hello_proto_rawDescGZIP(), []int{1}
}

var File_hello_pkg_grpc_pb_hello_proto protoreflect.FileDescriptor

var file_hello_pkg_grpc_pb_hello_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x62, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x0c, 0x0a, 0x0a, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x0a, 0x0a, 0x08, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x2c, 0x0a,
	0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x23, 0x0a, 0x03, 0x46, 0x6f, 0x6f, 0x12, 0x0e, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x6f, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x13, 0x5a, 0x11, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hello_pkg_grpc_pb_hello_proto_rawDescOnce sync.Once
	file_hello_pkg_grpc_pb_hello_proto_rawDescData = file_hello_pkg_grpc_pb_hello_proto_rawDesc
)

func file_hello_pkg_grpc_pb_hello_proto_rawDescGZIP() []byte {
	file_hello_pkg_grpc_pb_hello_proto_rawDescOnce.Do(func() {
		file_hello_pkg_grpc_pb_hello_proto_rawDescData = protoimpl.X.CompressGZIP(file_hello_pkg_grpc_pb_hello_proto_rawDescData)
	})
	return file_hello_pkg_grpc_pb_hello_proto_rawDescData
}

var file_hello_pkg_grpc_pb_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hello_pkg_grpc_pb_hello_proto_goTypes = []interface{}{
	(*FooRequest)(nil), // 0: pb.FooRequest
	(*FooReply)(nil),   // 1: pb.FooReply
}
var file_hello_pkg_grpc_pb_hello_proto_depIdxs = []int32{
	0, // 0: pb.Hello.Foo:input_type -> pb.FooRequest
	1, // 1: pb.Hello.Foo:output_type -> pb.FooReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hello_pkg_grpc_pb_hello_proto_init() }
func file_hello_pkg_grpc_pb_hello_proto_init() {
	if File_hello_pkg_grpc_pb_hello_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hello_pkg_grpc_pb_hello_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FooRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hello_pkg_grpc_pb_hello_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FooReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hello_pkg_grpc_pb_hello_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hello_pkg_grpc_pb_hello_proto_goTypes,
		DependencyIndexes: file_hello_pkg_grpc_pb_hello_proto_depIdxs,
		MessageInfos:      file_hello_pkg_grpc_pb_hello_proto_msgTypes,
	}.Build()
	File_hello_pkg_grpc_pb_hello_proto = out.File
	file_hello_pkg_grpc_pb_hello_proto_rawDesc = nil
	file_hello_pkg_grpc_pb_hello_proto_goTypes = nil
	file_hello_pkg_grpc_pb_hello_proto_depIdxs = nil
}
